In [ ]:
import numpy as np

Create a NumPy array of integers from 1 to 10 (inclusive).

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Reshape the array from the previous question into a 2x5 matrix.

In [ ]:
arr=arr.reshape(2,5)

Perform element-wise multiplication of two NumPy arrays:

In [ ]:
arr2=np.arange(11,21).reshape(2,5)
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr3 = (arr * arr2).reshape(2,5)
print("MULTIPLICATION", arr3)

MULTIPLICATION [[ 11  24  39  56  75]
 [ 96 119 144 171 200]]


#Create one multidimensional array of shape (3,4,2) and perform
#indexing and slicing on it.

In [ ]:
arr4 = np.arange(1, 25).reshape(3, 4, 2)
print("Original array:\n", arr4)

Original array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]


In [ ]:
print("Sliced arr[:, :2, :]:\n", arr4[:, :2, :])

Sliced arr[:, :2, :]:
 [[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [11 12]]

 [[17 18]
  [19 20]]]


In [ ]:
print("Element at arr[2][1][0]:", arr4[2][1][0])

Element at arr[2][1][0]: 19


Generate a 3x3 matrix with random values between 0 and 1.

In [ ]:
arr5=np.random.rand(3,3)
arr5

array([[0.92651338, 0.23030179, 0.83370809],
       [0.34374247, 0.45773872, 0.05678252],
       [0.9681788 , 0.88457644, 0.56534256]])

Create two 2d array and perform hstack and vstack.

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])


print("Array a:\n", a)
print("Array b:\n", b)

Array a:
 [[1 2 3]
 [4 5 6]]
Array b:
 [[ 7  8  9]
 [10 11 12]]


In [ ]:
hstacked = np.hstack((a, b))
print("Horizontal Stack:\n", hstacked)

Horizontal Stack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
vstacked = np.vstack((a, b))
print("Vertical Stack:\n", vstacked)

Vertical Stack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
